// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvwjbkmsvquokexrmgnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2d2pia21zdnF1b2tleHJtZ252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTE4NjQsImV4cCI6MjA3MDY4Nzg2NH0.JWUn7XU0-Lzikbw4DIDUsmnjwOR7L02hV1jAAwtyftE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});